# Generated by Django 5.2.3 on 2025-06-28 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre del Producto')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción detallada')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('stock', models.IntegerField(default=0, verbose_name='Cantidad en Stock')),
                ('codigo_sku', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código SKU')),
                ('categoria', models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoría')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Producto Activo')),
            ],
            options={
                'verbose_name': 'Producto de Ferretería',
                'verbose_name_plural': 'Productos de Ferretería',
                'ordering': ['nombre'],
            },
        ),
    ]
